version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing global dependencies...

  pre_build:
    commands:
      - echo Installing dependencies...
      - echo "Current directory:" && pwd
      - echo "Directory contents:" && ls -la
      - echo "Checking if query-profiler-frontend exists:" && ls -la query-profiler-frontend || echo "Directory not found"
      - cd query-profiler-frontend && npm install

  build:
    commands:
      - echo Running tests...
      - echo "Current directory:" && pwd
      - echo "Directory contents:" && ls -la
      - npm test -- --coverage --ci --watchAll=false
      - echo Building the React application...
      - export REACT_APP_API_URL=$API_URL && npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'query-profiler-frontend/build'

cache:
  paths:
    - 'query-profiler-frontend/node_modules/**/*'