apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: query-profiler-dashboard
  region: us-east-1

vpc:
  id: vpc-005a18a20efafbe8e
  subnets:
    public:
      us-east-1a:
        id: subnet-071f802c6e0b04cf2
      us-east-1b:
        id: subnet-09f928bdeb0ade386

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true